### ISSUE TITLE
All pokemon link scripts doesn't work.

### ISSUE THREAD

**Issue by host1126** [FlagBrew/PKSM-Scripts#15]
I'm using PKSM 7.0.1
Pokemon Link don't created in main menu after script injection.

**Comment by piepie62** [comment]
This is impressively noninformative. You haven't said which games these scripts are for and I can't even come close to understanding what "Pokémon Link don't created in main menu" means.

**Comment by host1126** [comment]
The game that is causing problems with scripting is XY.
![20190919_013135](https://user-images.githubusercontent.com/24352145/65167439-83e37580-da7d-11e9-91d0-db12d65ec364.jpg)
As far as I know, if you apply the script in the picture, the Pokemon link should be added to the main menu as follows, but the script does not change.
![K3FuU](https://user-images.githubusercontent.com/24352145/65167686-fe13fa00-da7d-11e9-8ba4-cf4496dede9e.jpg)

**Comment by piepie62** [comment]
From the creator: `The scripts unfortunately don’t unlock the Pokémon link option. You’ll have to find another way to unlock it. Such as with Pokémon Bank... I do not have the means to find the event flag`

**Comment by host1126** [comment]
Thank you for your reply. I unlocked Pokemon Link via PKHeX and the script works fine.

**Comment by piepie62** [comment]
Good to hear. Closing
