### ISSUE TITLE
Message not reset to empty string in black-city-white-forest.c

### ISSUE THREAD

**Issue by SpikyC** [FlagBrew/PKSM-Scripts#27]
The last characters of the string "`%s\nis already present`" are still visible when you select a trainer with a longer name that is already selected (i.e.: Frederic, "`Frederic\nis already present`") and then select another trainer, but with a shorter name (i.e.: Leo, "`Leo\nis already presentesent`").

**Comment by SpiredMoth** [comment]
I should have made this post a long time ago, but this script should be fixed now. It will be bundled in the next version of PKSM

If you want it sooner:
- right-click [this link](https://raw.githubusercontent.com/FlagBrew/PKSM-Scripts/master/src/bw/black-city-white-forest.c) and choose `Save As`
- copy/move the file into `/3ds/PKSM/scripts/bw` on your SD card (make any folders that don't exist)

Then to use it, in the Scripts section of PKSM, press `X` then select `black-city-white-forest.c`
