### ISSUE TITLE
[picoC] Empty Box/Bank/Party slot

### ISSUE THREAD

**Issue by Mathaeuz** [FlagBrew/PKSM-Scripts#29]
I'm building a **picoC** script to organize my boxes, reserving a single slot per species, according to Id, and dumping extra entries of the same species into the storage.
I can swap Pokemon just fine but I'm having issues **emptying** slots.

 Is there a standardized way to empty slots within the Api?

Thanks in advance,

Mathaeuz.

**Comment by piepie62** [comment]
That's actually super simple. Just use <destination>_inject_slot with a PKX argument that's filled with zeroes.

**Comment by Mathaeuz** [comment]
I attempted that at first but it seems it still displays "_No way to transfer between generations. Impossible species_", which is super weird. 
I guess Pokemon Id 0000 isn't welcome.

**Comment by piepie62** [comment]
Oh, really? That's a bug, sorry about that. I'll fix it right away for the next version.

**Comment by Mathaeuz** [comment]
I'll keep trying in the meanwhile. With some luck I'll poke a hole.
Thanks for the help!
