### ISSUE TITLE
Feature Request: Dex Injection of all Pokémon in Storage

### ISSUE THREAD

**Issue by VijoPlays** [FlagBrew/PKSM-Scripts#32]
**Problem:**
Dex injections right now only offer the options to edit the Dex to display every Pokémon as seen or caught. It'd be great if it were possible to check the Storage for every Pokémon in the boxes and then update the Dex accordingly (so that you can create your own 'living Dex').

If it doesn't work, or is much work (since afaik right now there's a Dex script for every Gen separately), that's fine - just something cool that I'm missing.

**Solution:**
Just a script (or a "Dump storage into Dex"-button) to dump the contents of the storage into the game's Dex.

**Alternative:**
One thing that works right now is to dump the whole storage, save and then swap the contents of the boxes again. Problem here is that any Pokémon caught in a newer Gen doesn't transfer (only one at a time by editing them).

**Additional context:**
As always, I am sorry if the above solutions exist/have been requested already, couldn't find anything with the words I searched by.

**Comment by SpiredMoth** [comment]
I should have made this post a while ago, but this script now exists. It will be bundled in the next version of PKSM

If you want it sooner:
- right-click [this link](https://raw.githubusercontent.com/FlagBrew/PKSM-Scripts/master/src/universal/inject-bank-to-dex.c) and choose `Save As`
- copy/move the file into `/3ds/PKSM/scripts/universal` on your SD card (make any folders that don't exist)

Then to use it, in the Scripts section of PKSM, press `Y` then press `X` and select `inject-bank-to-dex.c`

**Comment by VijoPlays** [comment]
Yoo, that's hype! And thanks for the headsup. 💙
