### ISSUE TITLE
Injector.c script does not inject wc3 files.

### ISSUE THREAD

**Issue by KeeveeKoomoo** [FlagBrew/PKSM-Scripts#37]
I was trying to inject event wonder cards into my pokemon emerald save, but the event section simply tells me to use the script "Injector.c". I did so after putting all of the gen 3 event files (including the e-reader files just to see what would happen) and when selecting an event from the list, it says I am using an invalid extension. If this is the case, what is the correct extension, and how would I go about converting the current files I own, to the correct extension?

**Comment by KeeveeKoomoo** [comment]
Thank you for the swift reply.
I got confused with the wc3 file extensions because of the existance of
both wc6 and wc7 files. Also, because I saw them in a zip file with a
standalone injector that later went on to be used by pkhex. Thanks for
clearing that up. If the "event" script is in the repository, can I use the
instructions shown to install it? If it is in the discord, and it is not
too much trouble, could you send it to me via email? I am currently using
an old smartphone and for the time being do not have discord available as
it is just incompatible with my device.
Thank you,
Keeveekoomoo

**Comment by KeeveeKoomoo** [comment]
Nevermind I received the notification through email so I thought you had for some reason sent the reply through email lmao

**Comment by piepie62** [comment]
Just looked through the repository and it is in here. Note that those instructions are for older versions: what you'll want to do is download [this file](https://github.com/FlagBrew/PKSM-Scripts/blob/master/src/universal/RSEFrLg%20-%20Inject%20Tickets.c) and place it in the folder `/3ds/PKSM/scripts/universal`. If that folder doesn't exist, just make it.

**Comment by KeeveeKoomoo** [comment]
Ok tysm just one question, I'm a github noob, how do I download that file lol?

**Comment by piepie62** [comment]
Hmm, now that you mention it, I don't actually see a download file button. Either download the entire repository (and either extract just that file or the entire `src/universal` folder, pick your poison) or just copy the contents into a new file in the proper location
