### ISSUE TITLE
Dream Radar Redirect script 

### ISSUE THREAD

**Issue by Jaxonos** [FlagBrew/PKSM-Scripts#41]
I have redirected dream radar to an nds rom using the script and now I can't get dream radar to recognize the cartridge version of the games. So how do I remove the redirect? 

Any help is appreciated. :)

If there is a forum better suited to my request please redirect me there as this is my first time posting and I don't know much about this site.

**Comment by GriffinG1** [comment]
Looks like patch exists at `/luma/titles/00040000000AE100/code.ips`. Delete that and it should remove the redirect

**Comment by Jaxonos** [comment]
> Looks like patch exists at `/luma/titles/00040000000AE100/code.ips`. Delete that and it should remove the redirect

Thanks. That fixed it. :)
