### ISSUE TITLE
Luma 3ds menu language

### ISSUE THREAD

**Issue by Apache712** [FlagBrew/PKSM-Scripts#43]
I don’t know what I did exactly but I did some research and found out. I accidentally change the language from English to Spanish on the menu of Luma. I would like to change it back to English. Can someone please help me I do not have access to a computer I just have my 3DS.
![image](https://user-images.githubusercontent.com/130305838/230785727-cdde6892-bace-47e8-afd7-bf4b83224e41.jpg)
![image](https://user-images.githubusercontent.com/130305838/230785762-6ae52401-ab38-484d-859b-342d7edf4c59.jpg)
You can reach me at jdvidana@gmail.com

**Comment by GriffinG1** [comment]
Completely out of scope for our org. I recommend you join the [Nintendo Homebrew Discord](https://discord.gg/C29hYvh) instead.

I have also snipped your email from your issue as a safety precaution.
