### ISSUE TITLE
Gen 6 Storage crash issue.

### ISSUE THREAD

**Issue by AshenDragon** [FlagBrew/PKSM-Scripts#5]
After using PKSM to store three pokemon i was trying to swap to a different game of the same version (Pokemon Y to Pokemon X) after cloning them the clones were put in the bank for an attempted transfer. PKSM loaded fine, Editor amd everything else was avaliable, except for storage, whih immediately brings me to the home screen not long after i try to open storage. Additional note: Said bank box they were placed in had indeed been renamed, said name included a / not sure if that is crucial.

**Comment by piepie62** [comment]
Wrong repository
